const express = require('express')
const router = express.Router()
const adminControl = require('../controllers/admin-control ')
const upload = require('../middlewares/multer')

router.get('/',adminControl.getDashboard)
router.get('/login',adminControl.getLogin)
router.get('/products',adminControl.getProductsList)
router.get('/addProducts',adminControl.getAddProducts)
router.post('/addProducts',upload.array('img',3),adminControl.postAddProducts)
router.route('/editProduct').get(adminControl.getEditProducts).post(adminControl.postEditProducts)
// router.get('/editProduct',adminControl.getEditProducts)
// router.post('/editProduct',adminControl.postEditProducts)
router.get('/deleteProduct',adminControl.getDeleteProduct)
router.post('/login',adminControl.postLogin)
router.get('/customers',adminControl.getCustomers)
router.get('/blockUser',adminControl.getBlockUser)
router.get('/unBlockUser',adminControl.getUnBlockUser)
router.get('/categoryList',adminControl.getCategory)
router.get('/addCategory',adminControl.getAddCategory)
router.post('/addCategory',adminControl.postAddCategory)
router.get('/deleteCategory',adminControl.getDeleteCategory)
router.get('/editCategory',adminControl.getEditCategory)
router.post('/editCategory',adminControl.postEditCategory)
router.get('/logout',adminControl.getAdminLogout)


module.exports = router