const express = require('express')
const router = express.Router()
const adminControl = require('../controllers/admin-control ')
const multer = require('../middlewares/multer')
const checkLoggedIn = require('../middlewares/adminLoggedInCheck')
const ProductUpload = multer.upload('productImages')
const CategoryUpload = multer.upload('categoryImages')


router.get('/',checkLoggedIn,adminControl.getDashboard)
router.get('/login',adminControl.getLogin)
router.get('/products',checkLoggedIn,adminControl.getProductsList)
router.get('/addProducts',checkLoggedIn,adminControl.getAddProducts)
router.post('/addProducts',checkLoggedIn,ProductUpload.array('img',3),adminControl.postAddProducts)
router.route('/editProduct').get(checkLoggedIn,adminControl.getEditProducts).post(checkLoggedIn,ProductUpload.array('img',3),adminControl.postEditProducts)
// router.get('/editProduct',adminControl.getEditProducts)
// router.post('/editProduct',adminControl.postEditProducts)
router.get('/deleteProduct',checkLoggedIn,adminControl.getDeleteProduct)
router.post('/login',adminControl.postLogin)
router.get('/customers',checkLoggedIn,adminControl.getCustomers)
router.get('/orders',checkLoggedIn,adminControl.getOrders)
router.get('/orderSummary',checkLoggedIn,adminControl.getOrderSummary)
router.post('/changeOrderStatus',checkLoggedIn,adminControl.getChangeOrderStatus)
router.get('/blockUser',checkLoggedIn,adminControl.getBlockUser)
router.get('/unBlockUser',checkLoggedIn,adminControl.getUnBlockUser)
router.get('/categoryList',checkLoggedIn,adminControl.getCategory)
router.get('/addCategory',checkLoggedIn,adminControl.getAddCategory)
router.post('/addCategory',checkLoggedIn,CategoryUpload.single('img'),adminControl.postAddCategory)
router.get('/deleteCategory',checkLoggedIn,adminControl.getDeleteCategory)
router.get('/editCategory',checkLoggedIn,adminControl.getEditCategory)
router.post('/editCategory',checkLoggedIn,adminControl.postEditCategory)
router.get('/logout',checkLoggedIn,adminControl.getAdminLogout)


module.exports = router