const express = require('express')
const multer = require('multer')
const router = express.Router()
const userControl = require('../controllers/user-control')
const checkLoggin = require('../middlewares/checkLoggedIn')
const checkAccess = require('../middlewares/checkBlockuser')




router.get('/',userControl.getIndex)
router.get('/login',userControl.getLogin)
router.post('/login',userControl.postLogin)
router.get('/signup',userControl.getSignup)
router.post('/signup',userControl.postSignup)
router.get('/verifyOtp',userControl.getVerifyOtp)
router.post('/verifyOtp',userControl.postVerifyOtp)
router.get('/resentOtp',userControl.getResetOtp)
router.get('/viewProduct',userControl.getViewProduct)
router.get('/cart',checkLoggin,checkAccess,userControl.getCart)
router.get('/logout',checkLoggin,checkAccess,userControl.getLogout)
router.post('/addToCart',checkLoggin,checkAccess,userControl.postAddToCart)
router.get('/addToCart',checkLoggin,checkAccess,userControl.getAddToCart)
router.get('/quantityInc',checkLoggin,checkAccess,userControl.getQuantityInc)
router.get('/quantityDec',checkLoggin,checkAccess,userControl.getQuantityDec)
router.get('/removeCartItem',checkLoggin,checkAccess,userControl.getRemoveCartItem)
router.get('/wishlist',checkLoggin,checkAccess,userControl.getWishlist)
router.get('/addToWishlist',checkLoggin,checkAccess,userControl.getAddToWishlist)
router.get('/removeFromWishlist',checkLoggin,checkAccess,userControl.getRemoveFromWishlist)
router.get('/checkStock',checkLoggin,checkAccess,userControl.checkStock)
router.get('/checkout',checkLoggin,checkAccess,userControl.getCheckOut)
router.post('/placeOrder',checkLoggin,checkAccess,userControl.getPlaceOrder)
router.get('/orders',checkLoggin,checkAccess,userControl.getMyOrders)
router.get('/orderSummary',checkLoggin,checkAccess,userControl.getOrderSummary)
router.post('/verifyPayment',checkLoggin,checkAccess,userControl.postVerifyPayment)
router.post('/paymentFailed',checkLoggin,checkAccess,userControl.postPaymentFailed)
router.get('/shop',userControl.getShop)
router.get('/CategoryFilter',userControl.getCategoryFilter)
router.get('/CategoryAll',userControl.getAllCategory)
router.get('/profile',checkLoggin,checkAccess,userControl.getProfile)
router.get('/addAddress',checkLoggin,checkAccess,userControl.getAddAddress)
router.post('/saveAddress',checkLoggin,checkAccess,userControl.postSaveAddress)
router.get('/deleteAddress',checkLoggin,checkAccess,userControl.getDeleteAddress)
router.get('/editAddress',checkLoggin,checkAccess,userControl.getEditAddress)
router.post('/editAddress',checkLoggin,checkAccess,userControl.postEditAddress)
router.post('/verifyCoupon',checkLoggin,checkAccess,userControl.verifyCoupon)
router.get('/cancelOrder',checkLoggin,checkAccess,userControl.getCancelOrder)




module.exports = router;